"use client"

// Datos base de visitas para cards (pantalla de inicio y listado)
export const visitasData = [
  {
    id: "VIS-2023-0001",
    tipo: "Acceso a obra",
    estado: "Pendiente",
    fecha: "30/04/2023",
    hora: "09:00",
    sitio: "Terminal 1",
    solicitante: "Juan Pérez",
    empresa: "Constructora ABC",
    personas: 3,
    vehiculos: 1,
    detalles: "Visita para inspección de avance de obra",
  },
  {
    id: "VIS-2023-0002",
    tipo: "Acceso a muelle",
    estado: "Aceptada",
    fecha: "30/04/2023",
    hora: "10:30",
    sitio: "Muelle Sur",
    solicitante: "María Rodríguez",
    empresa: "Naviera XYZ",
    personas: 2,
    vehiculos: 0,
    detalles: "Reunión con capitán de embarcación",
  },
  {
    id: "VIS-2023-0003",
    tipo: "Transporte cargas",
    estado: "Aceptada",
    fecha: "30/04/2023",
    hora: "14:00",
    sitio: "Almacén Central",
    solicitante: "Carlos Gómez",
    empresa: "Suministros Portuarios",
    personas: 2,
    vehiculos: 1,
    detalles: "Entrega de materiales para mantenimiento",
  },
  {
    id: "VIS-2023-0004",
    tipo: "Evento",
    estado: "En curso",
    fecha: "30/04/2023",
    hora: "15:30",
    sitio: "Terminal 2",
    solicitante: "Ana Martínez",
    empresa: "Ingeniería Portuaria",
    personas: 4,
    vehiculos: 2,
    detalles: "Inspección técnica de grúas",
  },
  {
    id: "VIS-2023-0005",
    tipo: "Laboral",
    estado: "Pendiente",
    fecha: "01/05/2023",
    hora: "10:00",
    sitio: "Oficinas Centrales",
    solicitante: "Roberto Sánchez",
    empresa: "Logística Marítima",
    personas: 2,
    vehiculos: 1,
    detalles: "Reunión de coordinación logística",
    personaAVisitar: "Marina López",
  },
  {
    id: "VIS-2023-0006",
    tipo: "Guiada",
    estado: "Aceptada",
    fecha: "02/05/2023",
    hora: "09:30",
    sitio: "Terminal 3",
    solicitante: "Laura González",
    empresa: "Inspecciones Técnicas",
    personas: 3,
    vehiculos: 1,
    detalles: "Inspección de seguridad",
  },
  {
    id: "VIS-2023-0007",
    tipo: "Transporte cargas",
    estado: "Finalizada",
    fecha: "05/05/2023",
    hora: "11:00",
    sitio: "Almacén Norte",
    solicitante: "Miguel Torres",
    empresa: "Suministros Navales",
    personas: 2,
    vehiculos: 1,
    detalles: "Entrega de equipamiento",
  },
  {
    id: "VIS-2023-0008",
    tipo: "Guiada",
    estado: "En curso",
    fecha: "06/05/2023",
    hora: "13:00",
    sitio: "Terminal Principal",
    solicitante: "Sofía Ramírez",
    empresa: "Escuela Técnica",
    personas: 20,
    vehiculos: 1,
    detalles: "Visita educativa de alumnos",
  },
  {
    id: "VIS-2023-0009",
    tipo: "Evento",
    estado: "Finalizada",
    fecha: "07/05/2023",
    hora: "16:00",
    sitio: "Terminal 4",
    solicitante: "Federico López",
    empresa: "Auditorías Marítimas",
    personas: 2,
    vehiculos: 0,
    detalles: "Auditoría anual de procesos",
  },
  {
    id: "VIS-2023-0010",
    tipo: "Guiada",
    estado: "Pendiente",
    fecha: "08/05/2023",
    hora: "10:00",
    sitio: "Terminal Principal",
    solicitante: "Sofía Ramírez",
    empresa: "Escuela Técnica",
    personas: 12,
    vehiculos: 1,
    detalles: "Visita educativa de alumnos",
  },
  {
    id: "VIS-2023-0011",
    tipo: "Evento",
    estado: "Aceptada",
    fecha: "08/05/2023",
    hora: "12:00",
    sitio: "Terminal 2",
    solicitante: "Carlos Gómez",
    empresa: "Inspecciones Técnicas",
    personas: 2,
    vehiculos: 1,
    detalles: "Inspección de seguridad",
  },
  {
    id: "VIS-2023-0012",
    tipo: "Evento",
    estado: "Rechazada",
    fecha: "30/04/2023",
    hora: "14:00",
    sitio: "Terminal 5",
    solicitante: "Federico López",
    empresa: "Auditorías Marítimas",
    personas: 2,
    vehiculos: 0,
    detalles: "Auditoría rechazada por documentación incompleta",
  },
  {
    id: "VIS-2023-0013",
    tipo: "Transporte cargas",
    estado: "Cancelada",
    fecha: "30/04/2023",
    hora: "15:30",
    sitio: "Almacén Sur",
    solicitante: "Miguel Torres",
    empresa: "Suministros Navales",
    personas: 1,
    vehiculos: 1,
    detalles: "Entrega cancelada por mal clima",
  },
  {
    id: "VIS-2023-0014",
    tipo: "Laboral",
    estado: "Pendiente",
    fecha: "15/07/2025",
    hora: "09:30",
    sitio: "Oficinas Centrales",
    solicitante: "Marina López",
    empresa: "Logística Marítima",
    personas: 3,
    vehiculos: 0,
    detalles: "Reunión de planificación semanal",
  },
  {
    id: "VIS-2023-0015",
    tipo: "Transporte cargas",
    estado: "Aceptada",
    fecha: "15/07/2025",
    hora: "11:00",
    sitio: "Almacén Norte",
    solicitante: "Javier Torres",
    empresa: "Suministros Navales",
    personas: 1,
    vehiculos: 1,
    detalles: "Entrega de repuestos",
  },
  {
    id: "VIS-2023-0016",
    tipo: "Evento",
    estado: "En curso",
    fecha: "15/07/2025",
    hora: "13:00",
    sitio: "Terminal 3",
    solicitante: "Laura González",
    empresa: "Inspecciones Técnicas",
    personas: 2,
    vehiculos: 1,
    detalles: "Inspección de seguridad mensual",
  },
  {
    id: "VIS-2023-0017",
    tipo: "Acceso a obra",
    estado: "Finalizada",
    fecha: "15/07/2025",
    hora: "15:00",
    sitio: "Terminal 1",
    solicitante: "Juan Pérez",
    empresa: "Constructora ABC",
    personas: 4,
    vehiculos: 2,
    detalles: "Cierre de obra parcial",
  },
  {
    id: "VIS-2023-0018",
    tipo: "Evento",
    estado: "Rechazada",
    fecha: "15/07/2025",
    hora: "16:30",
    sitio: "Terminal 4",
    solicitante: "Federico López",
    empresa: "Auditorías Marítimas",
    personas: 2,
    vehiculos: 0,
    detalles: "Auditoría rechazada por falta de documentación",
  },
  {
    id: "VIS-2023-0019",
    tipo: "Transporte cargas",
    estado: "Cancelada",
    fecha: "15/07/2025",
    hora: "17:00",
    sitio: "Almacén Sur",
    solicitante: "Miguel Torres",
    empresa: "Suministros Navales",
    personas: 1,
    vehiculos: 1,
    detalles: "Entrega cancelada por mal clima",
  },
]

// Detalles completos por ID para las pantallas de detalle
export const detallesVisitas = [
  {
    id: "VIS-2023-0001",
    tipo: "Acceso a obra",
    estado: "Pendiente",
    fechaIngreso: "30/04/2023 09:00",
    fechaEgreso: "30/04/2023 18:00",
    solicitante: "Juan Pérez",
    empresa: "Constructora ABC",
    destino: "Terminal 1",
    personas: [
      { nombre: "Juan Pérez", dni: "20.111.111", ingreso: true, egreso: false },
      { nombre: "Ana López", dni: "21.222.222", ingreso: true, egreso: false },
      { nombre: "Carlos Gómez", dni: "22.333.333", ingreso: false, egreso: false },
    ],
    vehiculos: [
      { patente: "AA 111 BB", tipo: "Camioneta", marca: "Toyota", ingreso: true, egreso: false },
    ],
  },
  {
    id: "VIS-2023-0002",
    tipo: "Acceso a muelle",
    estado: "Aceptada",
    fechaIngreso: "30/04/2023 10:30",
    fechaEgreso: "30/04/2023 12:00",
    solicitante: "María Rodríguez",
    empresa: "Naviera XYZ",
    destino: "Muelle Sur",
    personas: [
      { nombre: "María Rodríguez", dni: "23.444.444", ingreso: true, egreso: true },
      { nombre: "Pedro Suárez", dni: "24.555.555", ingreso: true, egreso: true },
    ],
    vehiculos: [],
  },
  {
    id: "VIS-2023-0003",
    tipo: "Transporte cargas",
    estado: "Aceptada",
    fechaIngreso: "30/04/2023 14:00",
    fechaEgreso: "30/04/2023 16:00",
    solicitante: "Carlos Gómez",
    empresa: "Suministros Portuarios",
    destino: "Almacén Central",
    personas: [
      { nombre: "Carlos Gómez", dni: "25.666.666", ingreso: true, egreso: true },
      { nombre: "Lucía Fernández", dni: "26.777.777", ingreso: true, egreso: true },
    ],
    vehiculos: [
      { patente: "BB 222 CC", tipo: "Camioneta", marca: "Ford", ingreso: true, egreso: true },
    ],
  },
  {
    id: "VIS-2023-0004",
    tipo: "Acceso a obra",
    estado: "En curso",
    fechaIngreso: "30/04/2023 15:30",
    fechaEgreso: "30/04/2023 17:00",
    solicitante: "Ana Martínez",
    empresa: "Ingeniería Portuaria",
    destino: "Terminal 2",
    personas: [
      { nombre: "Ana Martínez", dni: "27.888.888", ingreso: true, egreso: false },
      { nombre: "Roberto López", dni: "28.999.999", ingreso: true, egreso: false },
      { nombre: "Sofía García", dni: "30.000.000", ingreso: false, egreso: false },
    ],
    vehiculos: [
      { patente: "CC 333 DD", tipo: "Camioneta", marca: "Chevrolet", ingreso: true, egreso: false },
      { patente: "DD 444 EE", tipo: "Camioneta", marca: "Toyota", ingreso: true, egreso: false },
    ],
  },
  {
    id: "VIS-2023-0005",
    tipo: "Laboral",
    estado: "Pendiente",
    fechaIngreso: "01/05/2023 10:00",
    fechaEgreso: "01/05/2023 11:00",
    solicitante: "Roberto Sánchez",
    empresa: "Logística Marítima",
    destino: "Oficinas Centrales",
    personas: [
      { nombre: "Roberto Sánchez", dni: "31.111.111", ingreso: true, egreso: true },
      { nombre: "María González", dni: "32.222.222", ingreso: true, egreso: true },
    ],
    vehiculos: [],
  },
  {
    id: "VIS-2023-0006",
    tipo: "Guiada",
    estado: "Aceptada",
    fechaIngreso: "02/05/2023 09:30",
    fechaEgreso: "02/05/2023 11:00",
    solicitante: "Laura González",
    empresa: "Inspecciones Técnicas",
    destino: "Terminal 3",
    personas: [
      { nombre: "Laura González", dni: "33.333.333", ingreso: true, egreso: true },
      { nombre: "Pedro Ruiz", dni: "34.444.444", ingreso: true, egreso: true },
      { nombre: "Ana Martínez", dni: "35.555.555", ingreso: true, egreso: true },
    ],
    vehiculos: [
      { patente: "EE 555 FF", tipo: "Camioneta", marca: "Toyota", ingreso: true, egreso: true },
    ],
  },
  {
    id: "VIS-2023-0007",
    tipo: "Transporte cargas",
    estado: "Finalizada",
    fechaIngreso: "05/05/2023 11:00",
    fechaEgreso: "05/05/2023 12:00",
    solicitante: "Miguel Torres",
    empresa: "Suministros Navales",
    destino: "Almacén Norte",
    personas: [
      { nombre: "Miguel Torres", dni: "36.666.666", ingreso: true, egreso: true },
      { nombre: "Lucía García", dni: "37.777.777", ingreso: true, egreso: true },
    ],
    vehiculos: [
      { patente: "FF 666 GG", tipo: "Camioneta", marca: "Ford", ingreso: true, egreso: true },
    ],
  },
  {
    id: "VIS-2023-0008",
    tipo: "Guiada",
    estado: "En curso",
    fechaIngreso: "06/05/2023 13:00",
    fechaEgreso: "06/05/2023 14:00",
    solicitante: "Sofía Ramírez",
    empresa: "Escuela Técnica",
    destino: "Terminal Principal",
    personas: [
      { nombre: "Sofía Ramírez", dni: "38.888.888", email: "sofia@gmail.com", ingreso: true, egreso: false },
      { nombre: "Juan Pérez", dni: "20.111.111", ingreso: true, egreso: false },
      { nombre: "Ana López", dni: "21.222.222", ingreso: true, egreso: false },
      { nombre: "Carlos Gómez", dni: "22.333.333", ingreso: false, egreso: false },
      { nombre: "Lucía Fernández", dni: "23.444.555", ingreso: false, egreso: false },
      { nombre: "Pedro Suárez", dni: "24.555.666", ingreso: false, egreso: false },
      { nombre: "Marina López", dni: "25.666.777", ingreso: false, egreso: false },
      { nombre: "Federico López", dni: "26.777.888", ingreso: false, egreso: false },
      { nombre: "Laura González", dni: "27.888.999", ingreso: false, egreso: false },
      { nombre: "Javier Torres", dni: "28.999.000", ingreso: false, egreso: false },
      { nombre: "Miguel Torres", dni: "29.000.111", ingreso: false, egreso: false },
      { nombre: "Alberto Sagardoy", dni: "30.111.222", ingreso: false, egreso: false },
      { nombre: "María González", dni: "31.222.333", ingreso: false, egreso: false },
      { nombre: "Roberto Sánchez", dni: "32.333.444", ingreso: false, egreso: false },
      { nombre: "Luis Morales", dni: "33.444.555", ingreso: false, egreso: false },
      { nombre: "Ana Martínez", dni: "34.555.666", ingreso: false, egreso: false },
      { nombre: "Pedro Ruiz", dni: "35.666.777", ingreso: false, egreso: false },
      { nombre: "Lucía García", dni: "36.777.888", ingreso: false, egreso: false },
      { nombre: "Sofía García", dni: "37.888.999", ingreso: false, egreso: false },
      { nombre: "María Rodríguez", dni: "38.999.000", ingreso: false, egreso: false },
    ],
    vehiculos: [
      { patente: "GG 777 HH", tipo: "Camioneta", marca: "Toyota", ingreso: true, egreso: false },
    ],
  },
  {
    id: "VIS-2023-0009",
    tipo: "Evento",
    estado: "Finalizada",
    fechaIngreso: "07/05/2023 16:00",
    fechaEgreso: "07/05/2023 17:00",
    solicitante: "Federico López",
    empresa: "Auditorías Marítimas",
    destino: "Terminal 4",
    personas: [
      { nombre: "Federico López", dni: "39.999.999", ingreso: true, egreso: true },
      { nombre: "María Rodríguez", dni: "23.444.444", ingreso: true, egreso: true },
    ],
    vehiculos: [],
  },
  {
    id: "VIS-2023-0010",
    tipo: "Guiada",
    estado: "Pendiente",
    fechaIngreso: "08/05/2023 10:00",
    fechaEgreso: "08/05/2023 11:00",
    solicitante: "Sofía Ramírez",
    empresa: "Escuela Técnica",
    destino: "Terminal Principal",
    personas: [
      { nombre: "Sofía Ramírez", dni: "38.888.888", ingreso: true, egreso: false },
      { nombre: "Juan Pérez", dni: "20.111.111", ingreso: true, egreso: false },
      { nombre: "Ana López", dni: "21.222.222", ingreso: true, egreso: false },
      { nombre: "Carlos Gómez", dni: "22.333.333", ingreso: false, egreso: false },
    ],
    vehiculos: [
      { patente: "GG 777 HH", tipo: "Camioneta", marca: "Toyota", ingreso: true, egreso: false },
    ],
  },
  {
    id: "VIS-2023-0011",
    tipo: "Evento",
    estado: "Aceptada",
    fechaIngreso: "08/05/2023 12:00",
    fechaEgreso: "08/05/2023 13:00",
    solicitante: "Carlos Gómez",
    empresa: "Inspecciones Técnicas",
    destino: "Terminal 2",
    personas: [
      { nombre: "Carlos Gómez", dni: "25.666.666", ingreso: true, egreso: true },
      { nombre: "Lucía Fernández", dni: "26.777.777", ingreso: true, egreso: true },
    ],
    vehiculos: [
      { patente: "BB 222 CC", tipo: "Camioneta", marca: "Ford", ingreso: true, egreso: true },
    ],
  },
  {
    id: "VIS-2023-0012",
    tipo: "Evento",
    estado: "Rechazada",
    fechaIngreso: "30/04/2023 14:00",
    fechaEgreso: "30/04/2023 15:00",
    solicitante: "Federico López",
    empresa: "Auditorías Marítimas",
    destino: "Terminal 5",
    personas: [
      { nombre: "Federico López", dni: "39.999.999", ingreso: true, egreso: true },
      { nombre: "María Rodríguez", dni: "23.444.444", ingreso: true, egreso: true },
    ],
    vehiculos: [],
  },
  {
    id: "VIS-2023-0013",
    tipo: "Transporte cargas",
    estado: "Cancelada",
    fechaIngreso: "30/04/2023 15:30",
    fechaEgreso: "30/04/2023 16:30",
    solicitante: "Miguel Torres",
    empresa: "Suministros Navales",
    destino: "Almacén Sur",
    personas: [
      { nombre: "Miguel Torres", dni: "36.666.666", ingreso: true, egreso: true },
      { nombre: "Lucía García", dni: "37.777.777", ingreso: true, egreso: true },
    ],
    vehiculos: [
      { patente: "FF 666 GG", tipo: "Camioneta", marca: "Ford", ingreso: true, egreso: true },
    ],
  },
  {
    id: "VIS-2023-0014",
    tipo: "Laboral",
    estado: "Pendiente",
    fechaIngreso: "15/07/2025 09:30",
    fechaEgreso: "15/07/2025 10:30",
    solicitante: "Marina López",
    empresa: "Logística Marítima",
    destino: "Oficinas Centrales",
    personas: [
      { nombre: "Marina López", dni: "40.000.000", ingreso: true, egreso: true },
      { nombre: "Javier Torres", dni: "41.111.111", ingreso: true, egreso: true },
      { nombre: "Laura González", dni: "33.333.333", ingreso: true, egreso: true },
    ],
    vehiculos: [],
  },
  {
    id: "VIS-2023-0015",
    tipo: "Transporte cargas",
    estado: "Aceptada",
    fechaIngreso: "15/07/2025 11:00",
    fechaEgreso: "15/07/2025 12:00",
    solicitante: "Javier Torres",
    empresa: "Suministros Navales",
    destino: "Almacén Norte",
    personas: [
      { nombre: "Javier Torres", dni: "41.111.111", ingreso: true, egreso: true },
      { nombre: "Laura González", dni: "33.333.333", ingreso: true, egreso: true },
    ],
    vehiculos: [
      { patente: "EE 555 FF", tipo: "Camioneta", marca: "Toyota", ingreso: true, egreso: true },
    ],
  },
  {
    id: "VIS-2023-0016",
    tipo: "Evento",
    estado: "En curso",
    fechaIngreso: "15/07/2025 13:00",
    fechaEgreso: "15/07/2025 14:00",
    solicitante: "Laura González",
    empresa: "Inspecciones Técnicas",
    destino: "Terminal 3",
    personas: [
      { nombre: "Laura González", dni: "33.333.333", ingreso: true, egreso: true },
      { nombre: "Pedro Ruiz", dni: "34.444.444", ingreso: true, egreso: true },
    ],
    vehiculos: [
      { patente: "EE 555 FF", tipo: "Camioneta", marca: "Toyota", ingreso: true, egreso: true },
    ],
  },
  {
    id: "VIS-2023-0017",
    tipo: "Acceso a obra",
    estado: "Finalizada",
    fechaIngreso: "15/07/2025 15:00",
    fechaEgreso: "15/07/2025 16:00",
    solicitante: "Juan Pérez",
    empresa: "Constructora ABC",
    destino: "Terminal 1",
    personas: [
      { nombre: "Juan Pérez", dni: "20.111.111", ingreso: true, egreso: true },
      { nombre: "Ana López", dni: "21.222.222", ingreso: true, egreso: true },
      { nombre: "Carlos Gómez", dni: "22.333.333", ingreso: true, egreso: true },
    ],
    vehiculos: [
      { patente: "AA 111 BB", tipo: "Camioneta", marca: "Toyota", ingreso: true, egreso: true },
      { patente: "CC 333 DD", tipo: "Camioneta", marca: "Chevrolet", ingreso: true, egreso: true },
    ],
  },
  {
    id: "VIS-2023-0018",
    tipo: "Evento",
    estado: "Rechazada",
    fechaIngreso: "15/07/2025 16:30",
    fechaEgreso: "15/07/2025 17:30",
    solicitante: "Federico López",
    empresa: "Auditorías Marítimas",
    destino: "Terminal 4",
    personas: [
      { nombre: "Federico López", dni: "39.999.999", ingreso: true, egreso: true },
      { nombre: "María Rodríguez", dni: "23.444.444", ingreso: true, egreso: true },
    ],
    vehiculos: [],
  },
  {
    id: "VIS-2023-0019",
    tipo: "Transporte cargas",
    estado: "Cancelada",
    fechaIngreso: "15/07/2025 17:00",
    fechaEgreso: "15/07/2025 18:00",
    solicitante: "Miguel Torres",
    empresa: "Suministros Navales",
    destino: "Almacén Sur",
    personas: [
      { nombre: "Miguel Torres", dni: "36.666.666", ingreso: true, egreso: true },
      { nombre: "Lucía García", dni: "37.777.777", ingreso: true, egreso: true },
    ],
    vehiculos: [
      { patente: "FF 666 GG", tipo: "Camioneta", marca: "Ford", ingreso: true, egreso: true },
    ],
  },
]
